package cat.copernic.m03uf06review.hibernate;
// Generated 10-dic-2020 21:54:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer uid;
     private String nombre;
     private Set empleadoses = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(String nombre) {
        this.nombre = nombre;
    }
    public Departamentos(String nombre, Set empleadoses) {
       this.nombre = nombre;
       this.empleadoses = empleadoses;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }

    @Override
    public String toString() {
        return "Departamentos{" + "uid=" + uid + ", nombre=" + nombre + '}';
    }





}


