package cat.copernic.m03uf06review.hibernate;
// Generated 01-dic-2020 21:41:57 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer uid;
     private int edad;
     private String nombre;
     private double sueldo;
     private boolean contratadoActualmente;
     private Date fechaInicioContrato;
     private Date fechaFinContrato;
     private String plus;
     private char genero;

    public Empleados() {
    }

    public Empleados(int edad, String nombre, double sueldo, boolean contratadoActualmente, Date fechaInicioContrato, Date fechaFinContrato, String plus, char genero) {
       this.edad = edad;
       this.nombre = nombre;
       this.sueldo = sueldo;
       this.contratadoActualmente = contratadoActualmente;
       this.fechaInicioContrato = fechaInicioContrato;
       this.fechaFinContrato = fechaFinContrato;
       this.plus = plus;
       this.genero = genero;
    }
   
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public double getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(double sueldo) {
        this.sueldo = sueldo;
    }
    public boolean isContratadoActualmente() {
        return this.contratadoActualmente;
    }
    
    public void setContratadoActualmente(boolean contratadoActualmente) {
        this.contratadoActualmente = contratadoActualmente;
    }
    public Date getFechaInicioContrato() {
        return this.fechaInicioContrato;
    }
    
    public void setFechaInicioContrato(Date fechaInicioContrato) {
        this.fechaInicioContrato = fechaInicioContrato;
    }
    public Date getFechaFinContrato() {
        return this.fechaFinContrato;
    }
    
    public void setFechaFinContrato(Date fechaFinContrato) {
        this.fechaFinContrato = fechaFinContrato;
    }
    public String getPlus() {
        return this.plus;
    }
    
    public void setPlus(String plus) {
        this.plus = plus;
    }
    public char getGenero() {
        return this.genero;
    }
    
    public void setGenero(char genero) {
        this.genero = genero;
    }




}


